FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Add Jenkins to Docker group
RUN groupadd docker || true && \
    usermod -aG docker jenkins

USER jenkins